# Generated by Codex on 2026-04-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recruitment", "0002_candidateprofile_education_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="employer_type",
            field=models.CharField(
                choices=[
                    ("individual", "Personne physique"),
                    ("organization", "Institution"),
                ],
                default="organization",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="size",
            field=models.CharField(
                choices=[
                    ("self", "Independant"),
                    ("1-10", "1-10"),
                    ("11-50", "11-50"),
                    ("51-200", "51-200"),
                    ("201-500", "201-500"),
                    ("500+", "500+"),
                ],
                max_length=20,
            ),
        ),
    ]
