# Generated by Django 5.2.5 on 2026-08-10 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0005_alter_company_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='video_url',
            field=models.URLField(blank=True, help_text="Lien YouTube/Vimeo de presentation de l'entreprise"),
        ),
        migrations.CreateModel(
            name='CompanyPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='companies/photos/')),
                ('caption', models.CharField(blank=True, max_length=150)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='recruitment.company')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
