# Generated by Django 5.2.5 on 2026-09-02 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0006_company_video_url_companyphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='size',
            field=models.CharField(choices=[('self', 'Indépendant'), ('1-10', '1-10'), ('11-50', '11-50'), ('51-200', '51-200'), ('201-500', '201-500'), ('500+', '500+')], default='1-10', max_length=20),
        ),
        migrations.AlterField(
            model_name='company',
            name='video_url',
            field=models.URLField(blank=True, help_text="Lien YouTube/Vimeo de présentation de l'entreprise"),
        ),
        migrations.AlterField(
            model_name='interview',
            name='mode',
            field=models.CharField(choices=[('remote', 'Visio'), ('onsite', 'Présentiel')], default='remote', max_length=20),
        ),
        migrations.AlterField(
            model_name='interview',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Planifié'), ('confirmed', 'Confirmé'), ('done', 'Terminé'), ('cancelled', 'Annulé')], default='scheduled', max_length=20),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('received', 'Reçue'), ('in_process', 'En cours'), ('hired', 'Acceptée'), ('declined', 'Déclinée')], default='received', max_length=20),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publiée'), ('closed', 'Fermée')], default='draft', max_length=20),
        ),
    ]
