# Generated by Django 5.2.5 on 2026-09-02 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_passwordresetcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresetcode',
            name='purpose',
            field=models.CharField(choices=[('password_reset', 'Reinitialisation mot de passe'), ('email_verification', 'Verification email')], default='password_reset', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
