# Generated by Django 5.2.5 on 2026-09-02 02:23

from django.db import migrations


def mark_existing_users_verified(apps, schema_editor):
    # Les comptes crees avant l'ajout de la verification email par OTP
    # (superuser initial, comptes de demo deja crees pendant les tests de
    # deploiement) ne doivent pas se retrouver bloques a la connexion.
    User = apps.get_model('accounts', 'User')
    User.objects.update(email_verified=True)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_passwordresetcode_purpose_user_email_verified'),
    ]

    operations = [
        migrations.RunPython(mark_existing_users_verified, migrations.RunPython.noop),
    ]
