# Generated by Django 5.2.5 on 2026-09-02 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_backfill_email_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetcode',
            name='purpose',
            field=models.CharField(choices=[('password_reset', 'Réinitialisation mot de passe'), ('email_verification', 'Vérification email')], default='password_reset', max_length=20),
        ),
    ]
