export const companiesData = [
  {
    id: 1,
    name: "Sogebank",
    sector: "Banque",
    location: "Port-au-Prince",
    employees: "1000+ employés",
    offers: 12,
    size: "1000+",
    banner: "/banners/bank1.jpg",
    logo: "/logos/sogebank.png",
  },
  {
    id: 2,
    name: "Digicel",
    sector: "Tech",
    location: "Haïti",
    employees: "2000+ employés",
    offers: 14,
    size: "1000+",
    banner: "/banners/tech1.jpg",
    logo: "/logos/digicel.png",
  },
  {
    id: 3,
    name: "Hôpital Saint-Joseph",
    sector: "Santé",
    location: "Pétion-Ville",
    employees: "350 employés",
    offers: 3,
    size: "200-1000",
    banner: "/banners/hospital.jpg",
    logo: "/logos/default.png",
  },
  {
    id: 4,
    name: "Unibank",
    sector: "Banque",
    location: "Haïti",
    employees: "1500+ employés",
    offers: 8,
    size: "1000+",
    banner: "/banners/bank2.jpg",
    logo: "/logos/unibank.png",
  },
  {
    id: 5,
    name: "Capital Bank",
    sector: "Banque",
    location: "Pétion-Ville",
    employees: "800 employés",
    offers: 5,
    size: "200-1000",
    banner: "/banners/bank3.jpg",
    logo: "/logos/capitalbank.png",
  },
  {
    id: 6,
    name: "Natcom",
    sector: "Télécommunication",
    location: "Port-au-Prince",
    employees: "1500+ employés",
    offers: 9,
    size: "1000+",
    banner: "/banners/tech2.jpg",
    logo: "/logos/natcom.png",
  },
  {
    id: 7,
    name: "BRANA",
    sector: "Industrie / Agroalimentaire",
    location: "Port-au-Prince",
    employees: "900 employés",
    offers: 4,
    size: "200-1000",
    banner: "/banners/factory1.jpg",
    logo: "/logos/brana.png",
  },
  {
    id: 8,
    name: "Haytrac",
    sector: "Construction",
    location: "Haïti",
    employees: "400 employés",
    offers: 2,
    size: "200-1000",
    banner: "/banners/construction.jpg",
    logo: "/logos/haytrac.png",
  },
  {
    id: 9,
    name: "Hôpital Bernard Mevs",
    sector: "Santé",
    location: "Port-au-Prince",
    employees: "500 employés",
    offers: 6,
    size: "200-1000",
    banner: "/banners/hospital2.jpg",
    logo: "/logos/hopital.png",
  },
  {
    id: 10,
    name: "World Vision Haïti",
    sector: "ONG / Humanitaire",
    location: "Haïti",
    employees: "600 employés",
    offers: 7,
    size: "200-1000",
    banner: "/banners/ngo1.jpg",
    logo: "/logos/worldvision.png",
  },
  {
    id: 11,
    name: "CARE Haïti",
    sector: "ONG / Humanitaire",
    location: "Haïti",
    employees: "800 employés",
    offers: 5,
    size: "500+",
    banner: "/banners/ngo2.jpg",
    logo: "/logos/care.png",
  },
  {
    id: 12,
    name: "USAID Haïti",
    sector: "Coopération Internationale",
    location: "Port-au-Prince",
    employees: "900 employés",
    offers: 11,
    size: "500+",
    banner: "/banners/ngo3.jpg",
    logo: "/logos/usaid.png",
  },
  {
    id: 13,
    name: "FOKAL",
    sector: "Éducation / ONG",
    location: "Port-au-Prince",
    employees: "120 employés",
    offers: 2,
    size: "50-200",
    banner: "/banners/education1.jpg",
    logo: "/logos/fokal.png",
  },
  {
    id: 14,
    name: "Valerio Canez",
    sector: "Commerce / Distribution",
    location: "Port-au-Prince",
    employees: "300 employés",
    offers: 4,
    size: "200-1000",
    banner: "/banners/store1.jpg",
    logo: "/logos/valerio.png",
  },
  {
    id: 15,
    name: "Delimart",
    sector: "Supermarché",
    location: "Haïti",
    employees: "250 employés",
    offers: 3,
    size: "200-1000",
    banner: "/banners/store2.jpg",
    logo: "/logos/delimart.png",
  },
];
