# Generated by Django 5.2.5 on 2026-09-02 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='title',
            field=models.CharField(help_text='Rôle ou intitulé de poste, ex: UI Designer', max_length=150),
        ),
    ]
